CREATE TABLE IF NOT EXISTS customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL,
  company TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('Active', 'Inactive')),
  created_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
